version: 2
updates:
- package-ecosystem: gradle
  directory: "/modules/games"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: com.auth0:java-jwt
    versions:
    - 3.12.0
    - 3.12.1
  - dependency-name: org.springframework.boot
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.springframework.cloud:spring-cloud-dependencies
    versions:
    - Hoxton.SR9
- package-ecosystem: npm
  directory: "/modules/rules"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
