version: '3'
services:

  rules:
    build: ./rules/

  games:
    build: ./games/
    depends_on:
      - "rules"
      - "messaging"

  chess-diagrams:
    build: ./chess-diagrams/

  players:
      build: ./players/

  play:
    build: ./play/
    depends_on:
      - "games"
      - "players"
      - "chess-diagrams"

  reverse-proxy:
    build: ./reverse-proxy/
    ports:
      - "9000:80"
    depends_on:
      - "rules"
      - "games"
      - "chess-diagrams"
      - "play"

  computer-player:
    build: ./computer-player/
    depends_on:
      - "messaging"

  messaging:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
