version: '3'
services:

  homepage:
    build: ./homepage/
    environment:
      - JWT_COOKIE_NAME
      - JWT_SECRET


  rules:
    build: ./rules/

  games:
    build: ./games/
    depends_on:
      - "rules"
      - "messaging"
    environment:
      - JWT_COOKIE_NAME
      - JWT_SECRET
      - RABBITMQ_HOSTNAME=messaging
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD

  chess-diagrams:
    build: ./chess-diagrams/

  players:
      build: ./players/
      environment:
        - JWT_COOKIE_NAME
        - JWT_SECRET

  play:
    build: ./play/
    depends_on:
      - "games"
      - "players"
      - "chess-diagrams"

  reverse-proxy:
    build: ./reverse-proxy/
    ports:
      - "9000:80"
    depends_on:
      - "rules"
      - "games"
      - "chess-diagrams"
      - "play"

  computer-player:
    build: ./computer-player/
    depends_on:
      - "messaging"
    environment:
      - RABBITMQ_HOSTNAME=messaging
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD

  messaging:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
