version: '3'
services:

  homepage:
    build: ./homepage/
    environment:
      - JWT_COOKIE_NAME
      - JWT_SECRET


  rules:
    build: ./rules/

  games:
    build: ./games/
    depends_on:
      - "rules"
      - "messaging"
    environment:
      - JWT_COOKIE_NAME
      - JWT_SECRET
      - RABBITMQ_HOSTNAME=messaging
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD

  chess-diagrams:
    build: ./chess-diagrams/
    environment:
      - prometheus_multiproc_dir=.

  players:
      build: ./players/
      environment:
        - JWT_COOKIE_NAME
        - JWT_SECRET

  play:
    build: ./play/
    depends_on:
      - "games"
      - "players"
      - "chess-diagrams"

  reverse-proxy:
    build: ./reverse-proxy/
    ports:
      - "9000:80"
    depends_on:
      - "rules"
      - "games"
      - "chess-diagrams"
      - "play"

  computer-player:
    build: ./computer-player/
    depends_on:
      - "messaging"
    environment:
      - RABBITMQ_HOSTNAME=messaging
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD

  messaging:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"

  prometheus:
    image: "quay.io/prometheus/prometheus:v2.0.0"
    volumes:
     - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: "--config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus"
    ports:
     - 9090:9090

  grafana:
    image: "grafana/grafana:5.0.0"
    ports:
     - 3000:3000


  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  nginx-exporter:
    image: "nginx/nginx-prometheus-exporter:0.3.0"
    command: "-nginx.scrape-uri http://reverse-proxy:80/internal/basic_status"

